# Generated by Django 4.1 on 2024-09-20 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='month',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('user', 'category', 'month')},
        ),
    ]
